### ISSUE TITLE
Process never completes

### ISSUE THREAD

**Issue by rootwork** [swinton/screenshot-website#14]
I'm not sure which of the new changes might have caused this, but as of the [latest commit](https://github.com/swinton/screenshot-website/commit/90a849a1d2ab0eac808e532a155a96fcab449be3), when I try to run even the basic usage (one screenshot, one resolution, on ubuntu-latest) the action never completes. I don't get any error, it's just stuck on the screenshot step indefinitely -- I canceled it after 2 hours.

**Comment by wizche** [comment]
Same here, what I see is:
```
Run swinton/screenshot-website@v1.x
  with:
    source: http://www.centrometeolombardo.com/moduli/stazioni.php?lema
    destination: screenshot.png
    full-page: true
    delay: 0
Error: Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters Failed to deserialize params.width - BINDINGS: mandatory field missing at position 98
Error: The operation was canceled.
```

**Comment by wizche** [comment]
Looks like the issue is only when the width field is not passed, adding it makes the workflow complete correctly

**Comment by swinton** [comment]
I suspect this is the culprit: https://github.com/swinton/screenshot-website/commit/2567c41849d7bc33a9319cd30fa4b37f10d2796e

We may need a default for `width`:

https://github.com/swinton/screenshot-website/blob/2567c41849d7bc33a9319cd30fa4b37f10d2796e/action.yml#L19-L21

**Comment by swinton** [comment]
OK, should be fixed now and available in `v1.x`, I have test coverage for this here: https://github.com/swinton/screenshot-website/commit/3ed50013db6103103a23dfc0fcf04205bc66e0b6

Thanks for the bug report!

**Comment by wizche** [comment]
Thanks for the quick fix

**Comment by rootwork** [comment]
Thank you!

**Comment by danielo515** [comment]
It is still happening for me, and I'm using v1.X, can it be caused by something else?
